/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../api/supabaseService`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/users` | `/users`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ColorGuessingGame`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/../components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/../components/HelloWave`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ParallaxScrollView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../api/supabaseService`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/users` | `/users`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Collapsible`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ColorGuessingGame`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ExternalLink`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/HapticTab`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/HelloWave`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ParallaxScrollView`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../api/supabaseService${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/users${`?${string}` | `#${string}` | ''}` | `/users${`?${string}` | `#${string}` | ''}` | `/../components/Collapsible${`?${string}` | `#${string}` | ''}` | `/../components/ColorGuessingGame${`?${string}` | `#${string}` | ''}` | `/../components/ExternalLink${`?${string}` | `#${string}` | ''}` | `/../components/HapticTab${`?${string}` | `#${string}` | ''}` | `/../components/HelloWave${`?${string}` | `#${string}` | ''}` | `/../components/ParallaxScrollView${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../api/supabaseService`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/users` | `/users`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ColorGuessingGame`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/../components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/../components/HelloWave`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ParallaxScrollView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
